In [1]:
# # write a function to return percenatge of marks with assert condition that marks can't be (zero and negative).

def percentage(marks):
    for m in marks:
        assert m>0, "Only Positive marks"
        total = 500
    return (sum(marks)/total)*100
percentage([78,80,83,75,81])

79.4

In [3]:
#Write a Pandas program to create a DataFrame from a dictionary of lists, where: 
#• One column contains random integers between 10 and 100 (size=10). 
#• Another column contains random float values between 0 and 1. 
#• Extract the rows where the integer column values are divisible by 5 and the 
#float column values are greater than 0.5

import pandas as pd
import numpy as np

dic = {'col1':np.random.randint(10,101,size=10),
      'col2':np.random.uniform(0,1,size=10)}
df = pd.DataFrame(dic)
print(df)
cond1 = df.col1%5==0
cond2 = df.col2>0.5
df.loc[cond1&cond2]

   col1      col2
0    75  0.636374
1    13  0.294271
2    11  0.398409
3    95  0.132043
4    74  0.753356
5    86  0.106758
6    50  0.813804
7    77  0.718149
8    29  0.677720
9    80  0.884342

   col1      col2
0    75  0.636374
6    50  0.813804
9    80  0.884342

In [11]:
# Given a DataFrame with missing values: 
#•  Fill missing values in column A with the mean of the column. 
#•  Replace missing values in column B with the median. 
#•  Drop rows where column C has missing values. 
import pandas as pd
import numpy as np

data = {'A': [1, 2, np.nan, 4, 5], 
'B': [5, np.nan, np.nan, 8, 10], 
'C': ['a', 'b', np.nan, 'd', 'e']} 
df = pd.DataFrame(data) 
#print(df)
df["A"] = df["A"].fillna(df["A"].mean())
df["B"] = df["B"].fillna(df["B"].median())
df = df.dropna(subset= ["C"])
print(df)

     A     B  C
0  1.0   5.0  a
1  2.0   8.0  b
3  4.0   8.0  d
4  5.0  10.0  e

In [4]:
#Given a DataFrame of sales data: 
#•  Pivot the table to show total sales for each product across regions. 
#•  Add a new column to the pivot table that calculates the percentage of total sales for each 
#product.
    
data = {'Region': ['North', 'South', 'North', 'South', 'East'], 
'Product': ['A', 'A', 'B', 'B', 'C'], 
'Sales': [200, 150, 400, 300, 100]} 
df = pd.DataFrame(data) 
print(df)

df = df.pivot_table(values='Sales',index = 'Product' ,aggfunc='sum')
df['percent'] = (df['Sales']/df['Sales'].sum())*100

#df.pivot(index= 'Region', values = ['Sales', 'total sales'], columns ='Product' )

print(df)

  Region Product  Sales
0  North       A    200
1  South       A    150
2  North       B    400
3  South       B    300
4   East       C    100
         Sales    percent
Product
A          350  30.434783
B          700  60.869565
C          100   8.695652

In [5]:
# Write a custom function that: 
#• Takes a numeric value as input and returns 'High' if the value is above the mean of 
#the column, otherwise 'Low'. 
#• Apply this function to a column of random integers and add the results as a new 
#column. 
import numpy as np
import pandas as pd
data = {'col1': np.random.randint(1,10,size=5)}
df = pd.DataFrame(data)
print(df)
def custom(num, mean):
    return "High" if num>mean else "Low"
    
mean = df['col1'].mean()
df["Result"] = df["col1"].apply(lambda x:custom(x,mean))
df

   col1
0     2
1     3
2     7
3     8
4     4

   col1 Result
0     2    Low
1     3    Low
2     7   High
3     8   High
4     4    Low

In [16]:
#Create a Pandas Series of random integers between 1 and 100. Perform the following tasks: 
#1. Create a new series where all values that are greater than the 75th percentile of the 
#original series are replaced with the string 'High' and the rest are replaced with 'Low'. 
#2. Compute and display the cumulative sum of the series values

randVal= np.random.randint(1,101,size= 8)
S = pd.Series(randVal)
S

Sorted= np.sort(S)
n= len(Sorted)
pos= int(0.75*n)
percentile_75th = Sorted[pos]

new_series= S.apply(lambda x:"High" if x>percentile_75th else "Low")
print(new_series)

cum_sum = S.cumsum()
print(cum_sum)

0     Low
1     Low
2     Low
3    High
4     Low
5     Low
6     Low
7     Low
dtype: object
0     30
1     88
2    130
3    227
4    293
5    388
6    484
7    522
dtype: int64